import { bookStatsColumns } from './ratings.js';
export const publicColumns =
  'e.id,e.title,e.slug,e.author,e.description,e.short_description,e.category_id,e.language,e.pages,e.cover_path,e.sample_path,e.price,e.original_price,e.publication_date,e.learning_points,e.is_featured,e.is_bestseller,e.created_at,c.name as category,c.slug as category_slug,' +
  bookStatsColumns;
export const categories = [
  { id: '10000000-0000-4000-8000-000000000001', name: 'Technology', slug: 'technology' },
  { id: '10000000-0000-4000-8000-000000000002', name: 'Personal Growth', slug: 'personal-growth' },
  { id: '10000000-0000-4000-8000-000000000003', name: 'Business', slug: 'business' },
  { id: '10000000-0000-4000-8000-000000000004', name: 'Creativity', slug: 'creativity' },
];
export const demoBooks = [
  [
    'The Art of Deep Focus',
    'the-art-of-deep-focus',
    'Maya Bennett',
    1,
    34900,
    59900,
    184,
    'Make room for the work that matters. Build a calmer, more intentional relationship with your attention.',
  ],
  [
    'JavaScript, Clearly',
    'javascript-clearly',
    'Alex Morgan',
    0,
    49900,
    79900,
    256,
    'From your first function to confident applications. A practical companion for the modern web.',
  ],
  [
    'Build Something Good',
    'build-something-good',
    'Daniel Reed',
    2,
    44900,
    69900,
    212,
    'Turn a small idea into a thoughtful business, one useful decision at a time.',
  ],
  [
    'A Creative Practice',
    'a-creative-practice',
    'Sofia Chen',
    3,
    29900,
    49900,
    160,
    'Find inspiration in ordinary things and make creativity a part of your everyday life.',
  ],
  [
    'Small Steps, Lasting Change',
    'small-steps-lasting-change',
    'Emma Brooks',
    1,
    24900,
    39900,
    148,
    'A gentle, practical guide to building habits that fit the life you actually live.',
  ],
  [
    'Designing for People',
    'designing-for-people',
    'Oliver James',
    3,
    59900,
    89900,
    284,
    'An introduction to thoughtful design, meaningful questions, and products people love.',
  ],
].map((b, i) => ({
  id: `20000000-0000-4000-8000-00000000000${i + 1}`,
  title: b[0],
  slug: b[1],
  author: b[2],
  category_id: categories[b[3]].id,
  category: categories[b[3]].name,
  category_slug: categories[b[3]].slug,
  price: b[4],
  original_price: b[5],
  pages: b[6],
  description: b[7],
  short_description: b[7],
  language: 'English',
  average_rating: null,
  rating_count: 0,
  purchase_count: 0,
  cover_path: null,
  sample_path: null,
  is_featured: i < 4,
  is_bestseller: i === 0 || i === 2,
  publication_date: '2026-01-01',
  created_at: `2026-0${i + 1}-01T00:00:00Z`,
  learning_points: [
    'Build a strong foundation with clear explanations.',
    'Put new ideas into practice with reflective exercises.',
    'Create your own next steps for continued learning.',
  ],
}));
